
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cluster-open-cluster-management-io-v1beta1-backupschedule
  failurePolicy: Fail
  name: vbackupschedule.kb.io
  rules:
  - apiGroups:
    - cluster.open-cluster-management.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupschedules
  sideEffects: None
