
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - channels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - backups/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - backupschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - backupschedules/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - backupschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - channels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - restores/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - velero.io
  resources:
  - backups
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - velero.io
  resources:
  - deletebackuprequests
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - velero.io
  resources:
  - schedules
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
